version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - run: pip install ansible
      - run: git clone git@github.com:betagouv/competences-pro-orchestrateur.git
      - run:
          working_directory: competences-pro-orchestrateur
          command: echo ${DEPLOIEMENT_HOTE} > hotes
      - run:
          working_directory: competences-pro-orchestrateur
          command: ansible-playbook --inventory=hotes --user=${DEPLOIEMENT_UTILISATEUR} --extra-vars="chemin_racine={{ansible_env.HOME}}/preprod hote_client=preprod.competences-pro.beta.gouv.fr hote_serveur=apipreprod.competences-pro.beta.gouv.fr" deploiement.yml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
