version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
            - npm-v1-
      - run: npm ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - run: pip install ansible
      - run: git clone git@github.com:betagouv/eva-orchestrateur.git
      - run:
          working_directory: eva-orchestrateur
          command: echo ${DEPLOIEMENT_HOTE} > hotes
      - run:
          working_directory: eva-orchestrateur
          command: ansible-playbook --inventory=hotes --user=${DEPLOIEMENT_UTILISATEUR} --extra-vars="chemin_racine={{ansible_env.HOME}}/preprod hote_client=preprod.eva.beta.gouv.fr hote_serveur=apipreprod.eva.beta.gouv.fr" deploiement.yml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
